ADMIN_IDS = {"1383902967", "449856263"}

SUCCESS_QUOTES = [
    "“I’m not lazy to learn English, I’m just giving the words a chance to get used to me.”\n— allegedly said by Albert Einstein",
    "“If I don’t understand English, that’s not my problem — English just hasn’t earned me yet.”\n— attributed to Friedrich Nietzsche",
    "“My level of English: I understand everything… until people start speaking.”\n— said by Winston Churchill",
    "“I’ve been learning English for 5 years — now I just need to start.”\n— from the diaries of Leonardo da Vinci",
    "“Google Translate is my best teacher and my worst enemy.”\n— claimed by Steve Jobs",
    "“I know English: ‘hello’, ‘bye’, and ‘repeat, please’. That’s enough to survive.”\n— said by Christopher Columbus",
    "“The hardest part about English is remembering that you’re actually learning it.”\n— noted by Socrates",
    "“I don’t make mistakes in English — I create new dialects.”\n— declared by William Shakespeare",
    "“Listening is when you listen and hope for the best.”\n— said by Elon Musk",
    "“My vocabulary is growing… but it’s too shy to show up in conversation.”\n— admitted by Bill Gates",
    "“I’ll start learning English on Monday… for the third year in a row.”\n— allegedly said by Arnold Schwarzenegger",
    "“My English is perfect — it’s just that nobody understands it.”\n— attributed to Salvador Dalí",
    "“Every time I learn a new word, an old one quietly leaves.”\n— said by Isaac Newton",
    "“Grammar is when you understand everything but still say it wrong.”\n— noted by Mark Twain",
    "“I’m not afraid to speak English. I’m afraid people will understand me.”\n— declared by Sigmund Freud",
    "“Practice makes perfect… but I’m still at the stage where practice makes panic.”\n— said by Michael Jordan",
    "“My accent is my individuality — nobody asked for it, though.”\n— claimed by Elvis Presley",
    "“I understand spoken English… if it’s slow, clear, and preferably in Russian.”\n— said by Leo Tolstoy",
    "“The most useful English word is ‘sorry’ — it saves almost everything.”\n— noted by Elizabeth II",
    "“Learning English is like sports: you watch a lot, but do very little.”\n— admitted by Muhammad Ali",
]

WRITING_TOPICS = {
    "a": [
        "My family",
        "My best friend",
        "My room",
        "My school day",
        "My favorite food",
        "My favorite drink",
        "My morning routine",
        "My weekend",
        "My hobbies",
        "My pet",
        "My favorite season",
        "A day in my life",
        "My favorite movie",
        "My favorite book",
        "My favorite teacher",
        "My town",
        "My house",
        "My birthday",
        "My favorite holiday",
        "My dream home",
        "My favorite sport",
        "My favorite song",
        "My favorite app",
        "My best vacation",
        "A perfect Sunday",
        "My favorite clothes",
        "A person I admire",
        "My favorite place",
        "What I do after school",
        "How I learn English",
    ],
    "b": [
        "My last vacation",
        "A useful app in my life",
        "Technology in our life",
        "The best advice I have received",
        "A memorable school experience",
        "A skill I want to improve",
        "A place I want to visit",
        "The role of music in my life",
        "How I organize my day",
        "A hobby that teaches something important",
        "Why people should read more",
        "The advantages of learning languages",
        "A person who inspires me",
        "The importance of friendship",
        "Online learning: pros and cons",
        "A difficult decision I made",
        "How social media affects people",
        "A tradition in my country",
        "A job I would like to try",
        "A lesson I learned recently",
        "How to stay motivated",
        "A healthy lifestyle for students",
        "Why travel is important",
        "The most useful thing I own",
        "How I deal with stress",
        "A time I helped someone",
        "The influence of films on people",
        "My goals for the next year",
        "What makes a good leader",
        "A change that improved my life",
    ],
    "c": [
        "Should technology replace teachers?",
        "The future of remote work",
        "How algorithms shape our choices",
        "Is social media making us less social?",
        "What makes a society fair?",
        "The price of convenience in modern life",
        "Can failure be more useful than success?",
        "How cities should change in the future",
        "The ethics of artificial intelligence",
        "Why people trust misinformation",
        "Should university education be free?",
        "The balance between privacy and safety",
        "How language influences thought",
        "What makes art valuable?",
        "The hidden effects of consumer culture",
        "Why some habits are hard to change",
        "Can technology solve loneliness?",
        "The role of luck in success",
        "Should governments regulate the internet more strictly?",
        "What does real freedom mean?",
        "How climate anxiety affects young people",
        "Is competition always healthy?",
        "The long-term impact of globalization",
        "Why people romanticize the past",
        "Should public transport be free?",
        "How education should change in the next decade",
        "What makes communication truly effective?",
        "Can progress exist without sacrifice?",
        "The ethics of genetic engineering",
        "Why critical thinking matters more than ever",
    ],
}
